### ISSUE TITLE
Remove unused type packages

### ISSUE THREAD

**Issue by shunkica** [jeffijoe/typesync#101]
I am not 100% sure about this claim, but I think that prior to 0.11.0 this package used to remove type packages which are not used? (eg. from packages which were removed)

I can not test previous versions to verify this because they do not work anymore. ( getaddrinfo ENOTFOUND typespublisher.blob.core.windows.net )

In any case versions 0.11.0 and 0.11.1 do not remove unused type packages. Is there some flag I can pass to remove them?

**Comment by jeffijoe** [comment]
See https://github.com/jeffijoe/typesync/pull/97
