### ISSUE TITLE
failed to detect missing @types for `nock`

### ISSUE THREAD

**Issue by vassudanagunta** [jeffijoe/typesync#103]
I have `"nock": "^13.4.0"` in `devDependencies`, with no `"@types/nock"` entry.

`typesync` did not detect that `"@types/nock": "^11.1.0"` was available.

**Comment by jeffijoe** [comment]
That is because the `@types/nock` package [is deprecated](https://www.npmjs.com/package/@types/nock). TypeSync [does not add typings](https://github.com/jeffijoe/typesync/pull/98) for deprecated typings packages, as a deprecation usually means the library now ships with its own typings.
