### ISSUE TITLE
Version is not updated

### ISSUE THREAD

**Issue by menelaos** [jeffijoe/typesync#108]
**Steps to reproduce:**

1. `npx create-react-app foo --template typescript`
2. `cd foo`
3. Open `package.json` and change the version of `@types/react` to e.g. `^17.0.0`.
4. `npx typesync`

**Expected behaviour:**

`typesync` updates `@types/react` to a version that is compatible with the installed `react` version.

**Actual behaviour:**

`typesync` does not update the `@types/react` version and leaves it at `^17.0.0`.

**Comment by jeffijoe** [comment]
TypeSync doesn't update the typings packages, it only adds missing ones. I recommend using `npm-check` for upgrading packages.
