### ISSUE TITLE
Does not add types for jest

### ISSUE THREAD

**Issue by mkelley33** [jeffijoe/typesync#109]
I ran `npx typesync` and it told me I was all synced up, but when I ran `npm i -D @types/jest`, the red underlines beneath jest in VS Code disappeared. Note: When I installed the types for jest the version didn't match the jest version as recommended, but it made the red underlines go away in VS Code. If this isn't the correct approach, please let me know, and I'll close the issue.

**Comment by jeffijoe** [comment]
Typings should be included with Jest. However I have noticed myself that the types on DT are better. Sadly thats just an outlier.
