### ISSUE TITLE
Support yarn workspaces, lerna packages

### ISSUE THREAD

**Issue by dylang** [jeffijoe/typesync#11]
Yarn natively supports monoropos through a setting called `workspaces`.
When using `npm`, a project called `lerna` has a `packages` setting.

* https://yarnpkg.com/lang/en/docs/workspaces/
* https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/
* https://github.com/lerna/lerna#lernajson

The `workspaces` config in the root `package.json`, or `packages` in `lerna.json` lists glob patterns for all the workspaces.

If `typesync` is run in a project with workspaces, it would be great if it ran across all of the workspaces simultaneously. 

A workaround is to run `yarn lerna exec typesync` to execute `typesync` in every package directory, but it's much slower because it's spawning a copy of `typesync` for each `package.json`. My repo has 40+ packages and lots of duplication between them.

**Comment by dylang** [comment]
It's both simultaneously overly verbose and not helpful when running through `lerna exec`:

Here's a small snippet, this goes on for pages.

```
»  TypeSync v0.3.1
✔  1 typings added:
+  @types/is-ci

✨  Go ahead and run npm install or yarn to install the packages that were added.
»  TypeSync v0.3.1
»  TypeSync v0.3.1
»  TypeSync v0.3.1
⠋  Syncing type definitions in package.json...»  TypeSync v0.3.1
✔  No new typings added, looks like you're all synced up!
✔  No new typings added, looks like you're all synced up!
✔  1 typings added:
+  @types/is-ci

✨  Go ahead and run npm install or yarn to install the packages that were added.
⠴  Syncing type definitions in package.json...»  TypeSync v0.3.1
⠋  Syncing type definitions in package.json...»  TypeSync v0.3.1
⠙  Syncing type definitions in package.json...»  TypeSync v0.3.1
✔  No new typings added, looks like you're all synced up!
✔  2 typings added:
+  @types/git-branch
+  @types/is-ci

✨  Go ahead and run npm install or yarn to install the packages that were added.
✔  No new typings added, looks like you're all synced up!
✔  No new typings added, looks like you're all synced up!
»  TypeSync v0.3.1
»  TypeSync v0.3.1
✔  No new typings added, looks like you're all synced up!
✔  No new typings added, looks like you're all synced up!
»  TypeSync v0.3.1
»  TypeSync v0.3.1
»  TypeSync v0.3.1
⠋  Syncing type definitions in package.json...⠋  Syncing type definitions in package.json...»  TypeSync v0.3.1
✔  No new typings added, looks like you're all synced up!
✔  No new typings added, looks like you're all synced up!
✔  No new typings added, looks like you're all synced up!
✔  No new typings added, looks like you're all synced up!
»  TypeSync v0.3.1
⠋  Syncing type definitions in package.json...»  TypeSync v0.3.1
⠋  Syncing type definitions in package.json...»  TypeSync v0.3.1
⠋  Syncing type definitions in package.json...»  TypeSync v0.3.1
✔  No new typings added, looks like you're all synced up!
✔  1 typings added:
+  @types/is-ci
...cut...
```

**Comment by jeffijoe** [comment]
@dylang what do you think of this?

![image](https://user-images.githubusercontent.com/2505474/46597911-658d9f80-cae2-11e8-9d8a-7116ab7d2753.png)

**Comment by jeffijoe** [comment]
Implemented as of v0.4.0.

**Comment by dylang** [comment]
Amazing job, works great!

**Comment by wldcordeiro** [comment]
This is pretty great, but with lerna at least most people would put all the type defs in the root `devDependencies` rather than spread across the packages. 🤷‍♂️

**Comment by jeffijoe** [comment]
I use neither, so I don't know what people do and don't do. 🤷‍♂️ Whatever the behavior needs to be, it needs to be consistent across both.
