### ISSUE TITLE
Support PNPM Monorepos

### ISSUE THREAD

**Issue by lishaduck** [jeffijoe/typesync#118]
Many monorepos these days use pnpm. It uses a different format for specifying workspaces.
I'd be happy to add support sometime if you'd be willing to review a PR.

Discovered while investigating #116.

**Comment by jeffijoe** [comment]
Sure! Will it be a big change?

**Comment by lishaduck** [comment]
> Sure! Will it be a big change?

Ehh. It'd require reading `pnpm-workspace.yaml` and extracting out the `projects` key. Not too bad, but the way it's stored right now might need some refactoring. And we'd need a yaml parser. As this uses cosmiconfig, I figure we could use js-yaml to keep the size down, as that's what cosmiconfig uses.

**Comment by lishaduck** [comment]
YESITY YESITY YESITY YES!!!!

I did it 🥳

😉
