### ISSUE TITLE
honor yarn `save-exact` setting

### ISSUE THREAD

**Issue by dylang** [jeffijoe/typesync#12]
We use [renovate](https://renovatebot.com/) to keep our dependencies up-to-date, and it recommends not including `^` or `~` in the semver version in `package.json` files so that it can test all version upgrades before merging them.

`yarn` has a setting for this:
```
save-exact true
```

It would be helpful if `typesync` honored that config.

There might be a similar setting for `npm`.

**Comment by jeffijoe** [comment]
Currently typesync always adds the latest version of typings, but maybe it should look for a version that matches the semver of the package and write it out in the same format. That's more work though, and not sure if it's that valuable. If yarn upgrade-interactive still lists updates for packages with no prefixed version, I would not be opposed to making typesync write the exact version always.

**Comment by dylang** [comment]
That sounds like an even better idea, good thinking!

**Comment by jeffijoe** [comment]
Implemented as of v0.4.0.

**Comment by dylang** [comment]
Amazing job, works great!
