### ISSUE TITLE
Version mismatch is not caught or fixed

### ISSUE THREAD

**Issue by kimamula** [jeffijoe/typesync#121]
### Actual behavior

When I have this package.json:

```json
{
  "devDependencies": {
    "@types/react": "^17.0.80"
  },
  "dependencies": {
    "react": "^18.3.1"
  }
}
```

and run `npx typesync`, typesync doesn't update package.json. Also, `npx typesync --dry=fail` doesn't catch the version mismatch.

### Expected behavior

`npx typesync` should update package.json to update the version of `@types/react` so that it matches the version of `react`.  `npx typesync --dry=fail` should fail.

**Comment by jeffijoe** [comment]
TypeSync does not update package versions, it only adds missing typings. To update packages, consider using [`npm-check`](https://www.npmjs.com/package/npm-check).
