### ISSUE TITLE
Allow to exclude workspace' packages by paths

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [jeffijoe/typesync#123]
[Now that typesync works seamlessly in monorepos](https://github.com/jeffijoe/typesync/pull/119), there are multiple package.json that gets scanned.
But it would be very useful to have the option to exclude certain projects/packages by path.

```ts
// .typesyncrc
{
  "ignoreProjects": ["apps/acme-docs"]
}

**Comment by jeffijoe** [comment]
@lishaduck monorepo support is your baby, want to take a stab at this? 😄

**Comment by lishaduck** [comment]
Hmmm. Shouldn't be to bad.
School's a bit hectic, but if I can find some time, I'll take a look.

Ought to just be reading the exclusions and adding a `.filter()` call to one of these two functions: https://github.com/jeffijoe/typesync/blob/511cf396865b251a3a6a9875010c4dccded8a2df/src/workspace-resolver.ts#L95-L125

At this point, I should just write it 🙃

**Comment by lishaduck** [comment]
Hurrah! I fixed CI for the project I use this in, so I'll try to get to this sometime today.
