### ISSUE TITLE
--dry=fail option should detail what deps are missing

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [jeffijoe/typesync#125]
There is no reason to hide this information.

**Comment by jeffijoe** [comment]
Good point.

**Comment by Benjamin-Frost** [comment]
Hi @jeffijoe, I'm interested in contributing to this project for Hacktoberfest and would love to work on this issue. Could I take a shot at it?

**Comment by jeffijoe** [comment]
@Benjamin-Frost absolutely! 🙌
