### ISSUE TITLE
EISDIR error on 0.13.1 and 0.13.2

### ISSUE THREAD

**Issue by bduff9** [jeffijoe/typesync#128]
Hello!  We have been using your tool for a while however it started breaking today for us on the latest version.  0.13.1 also breaks with the below error however 0.13.0 works fine.

```bash
❯ npx typesync
»  TypeSync v0.13.2
✖  EISDIR: illegal operation on a directory, read
Stack:
Error: EISDIR: illegal operation on a directory, read
```

**Comment by jeffijoe** [comment]
@lishaduck this seems like it could be related to #126 ?

**Comment by lishaduck** [comment]
Oh, yeah. Everything was mocked in tests, so it didn't verify dir/file differences.
I'll take a look.

**Comment by lishaduck** [comment]
Funny, dependabot just tried to update it in my project: https://github.com/PSDTools/psdtools.github.io/actions/runs/11505963460/job/32028840120

**Comment by jeffijoe** [comment]
Since I can't reproduce this myself (I don't use workspaces), I'm gonna need one of you to try this alpha release to see if adding `nodir` to `glob` does the trick: `typesync@0.13.3-alpha.0`

**Comment by lishaduck** [comment]
No, now it doesn't get the workspaces at all.

**Comment by jeffijoe** [comment]
I'm not sure where it's attempting tor read a directory as a file - we only read files in 2 places, the workspace resolver and the package json file, and the former is wrapped in a try-catch.

**Comment by lishaduck** [comment]
Ok, figured it out. readPackageFile expects a package.json, but I gave it a directory. I'll look into it further.

**Comment by lishaduck** [comment]
Ok, I think I fixed it (it was a bug in my original impl, but I'd worked around it without realizing it; I fixed _the workaround_ #126, but then the bug was exposed). I'll test it and probably send in a PR in ~2 hours.

**Comment by jeffijoe** [comment]
0.13.3 released, thanks @lishaduck !

**Comment by lishaduck** [comment]
Do you want to deprecate 0.13.1 & .2?

**Comment by jeffijoe** [comment]
Done.
