### ISSUE TITLE
reduce unused typing package

### ISSUE THREAD

**Issue by septs** [jeffijoe/typesync#35]
```bash
# install package
npm install history

# sync typing
typesync

# uninstall package
npm uninstall history

# re-sync typing
typesync # should need to remove @types/history
```

1. the issue can use `m`(modules) field for check in  `search-index-min.json`.
2. package with `g`(globals) field have side effects
e.q: `@types/jquery` only use typing

`search-index-min.json` structure definition:
https://github.com/microsoft/types-publisher/blob/467eb14e3fe0204aa0f5e06549271fa4bea457e1/src/create-search-index.ts#L21-L34

**Comment by jeffijoe** [comment]
Doing this would automatically uninstall ambient typings like `@types/node` which is undesirable.

**Comment by septs** [comment]
@jeffijoe include global definition cannot be removed

![image](https://user-images.githubusercontent.com/3842474/62826454-5f7aba80-bbee-11e9-9506-b700b3ac6f01.png)

**Comment by septs** [comment]
This idea can only be processed without a global definition because he has no side effects.

**Comment by septs** [comment]
```
➜  Downloads cat search-index-min.json | jq '(.[].g | length) == 0' | grep 'true' | wc -l
    4880
➜  Downloads cat search-index-min.json | jq '(.[].g | length) > 0' | grep 'true' | wc -l
    1166
```
