### ISSUE TITLE
Typesync doesn't find @google-cloud/storage type definition

### ISSUE THREAD

**Issue by BruceHem** [jeffijoe/typesync#4]
@jeffijoe can u make this possible? 

module is `@google-cloud/storage`
and type definition file is `@types/google-cloud__storage`

**Comment by jeffijoe** [comment]
For sure! Is this how all scoped packages are typed? Do they all use the `@types/scope__package` format?

**Comment by BruceHem** [comment]
Can't say, I'm not sure

**Comment by jeffijoe** [comment]
From what I can tell, that is the case. I'll get this implemented soon, thanks for reporting!

**Comment by jeffijoe** [comment]
@BruceHem pushed to npm as 0.2.5 — thanks for reporting!
