### ISSUE TITLE
add `typesync install` command?

### ISSUE THREAD

**Issue by septs** [jeffijoe/typesync#41]
update `package.json` file after,
call package installer (npm OR yarn)

cases:
1. both (not)? exists `package-lock.json` and  `yarn.lock` files, after rejection install.
2. only exists `package-lock.json`, use `npm install` command install.
3. only exists `yarn.lock`, use `yarn install` command install.

see https://yarnpkg.com/lang/en/docs/yarn-lock/
see https://docs.npmjs.com/files/package-lock.json

**Comment by jeffijoe** [comment]
Hi @septs!

This is sort of a dupe of #3 — the cost vs benefit of this does not make it worthwhile. Simply doing `&& npm install` or `&& yarn install` after `typesync` is not much effort.
