### ISSUE TITLE
[feature] inculde types references from tsconfig

### ISSUE THREAD

**Issue by luckylooke** [jeffijoe/typesync#42]
Hi, thank you for your package!

Could you please add feature that typesync will look into tsconfig.json -> compilerOptions -> types and add also those '@types' into package json? https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types

Thanks :)

**Comment by jeffijoe** [comment]
I've never used that property, why is it needed? At that point, just doing `npm i --save-dev @types/node` (or whichever) seems easier and not worth the effort required to add it to TypeSync?

**Comment by luckylooke** [comment]
> I've never used that property, why is it needed?
for example typescript tests dependencies
I have created new Vue CLI project and it generates tsconfig with:
```
 "types": [
      "webpack-env",
      "mocha",
      "chai"
    ],
```
I wanted to run typecheck in parallel task with lints in my gitlab CI, so I need to have correct types in node_modules installed
but anyway.. I have tried to install those manually and find out that the problem is much more complex... so at the end I have removed type checking at the beginning of the pipeline and let it fail on build instead. Thank you for your time 👍
