### ISSUE TITLE
[feature request] Remove @types packages for packages already including types.

### ISSUE THREAD

**Issue by dylang** [jeffijoe/typesync#43]
Lot of packages are starting to include their own types, making the `@types` typings unnecessary for those packages. 

TypeScript will ignore the `@types` typings if a package includes types, but I don't know of an automated way to figure out which `@types` typings are no longer necessary and remove them.

Perhaps this project could handle cleaning up the redundant/outdated `@types` packages?

**Comment by jeffijoe** [comment]
I believe TypeSync already does this. For example, it won’t add typings for jest because they are included.

**Comment by dylang** [comment]
@jeffijoe If your `package.json` _already_ has `@types/jest`, then it would be great if TypeSync _removed_ it from the `package.json`, assuming TypeSync recognized it as no longer necessary because `jest` included the types.

**Comment by jeffijoe** [comment]
That would be a bad idea, because sometimes the typings from DT are more correct than the ones shipping with the package. Jest is one of those.

**Comment by dylang** [comment]
Interesting, I didn't realize TypeScript would use the `@types` if the package included types too. Thanks for helping me understand and closing this ticket!

**Comment by jeffijoe** [comment]
No problem! 👍
