### ISSUE TITLE
Add typesync rc file support

### ISSUE THREAD

**Issue by septs** [jeffijoe/typesync#47]
Configure ignore dependencies, ignore packages, etc via typesync rc file.

sample file path:
```
project directory/.typesync-rc.json
project directory/[any first-level subdirectory]/.typesync-rc.json
```

sample file format:
```json
{
  "ignoreDependencies": ["peer"],
  "ignorePackages": ["express"]
}
```

**Comment by jeffijoe** [comment]
What is the difference between "dependencies" and "packages"? I find them ambiguous.

**Comment by septs** [comment]
`ignoreDependencies` is to keep this feature

https://github.com/jeffijoe/typesync/blob/23f8a5cb842f0fcf42e839b329c2c103823ab368/README.md#L40-L48

**Comment by septs** [comment]
`ignorePackages` is ignore specific single package,
e.q: #46 the case

**Comment by jeffijoe** [comment]
Ah gotcha!

**Comment by septs** [comment]
I don't know where the entry settings for loading configuration file should be
If you can tell me, I can submit a pull request

**Comment by jeffijoe** [comment]
Could use cosmoconfig and put it behind a configuration service so it can be faked for testing.
