### ISSUE TITLE
can we have an option to have all @types only on root package.json of monorepo?

### ISSUE THREAD

**Issue by sibelius** [jeffijoe/typesync#51]
we install @types for all monorepo packages inside root package.json, so we don't need to install them in every single package of the monorepo

can we add an option for this behavior?

it should search all package.json, and install all @types of all packages inside the root package.json

**Comment by jeffijoe** [comment]
Would it make sense to make this the default behavior instead? I never used monorepos so I don't know the workflow.

**Comment by sibelius** [comment]
For me yes, not sure for everybody else

**Comment by vijaybritto** [comment]
What happens when different versions of the same package exist? How will code editors figure out that we require v1 of types in a package and v2 in other?

**Comment by jaburx** [comment]
Types should be hooked into the root `package.json` only if they have same version for all packages.

**Comment by sibelius** [comment]
we always try to upgrade all packages to the same versions

**Comment by sibelius** [comment]
it is better to keep @types in packages they belong
