### ISSUE TITLE
Possible to use programmatically?

### ISSUE THREAD

**Issue by voxpelli** [jeffijoe/typesync#54]
Is the only way to use this tool to do so through its CLI?

The `main` file in the `package.json` appears to be non-existent? https://github.com/jeffijoe/typesync/blob/81a10e96a73a2948950513892318cc4e23ffe99c/package.json#L15

I'm working on a tool where I thought it would be neat to allow one to use the result of typesync as one input, but wouldn't want to depend on private API:s.

**Comment by jeffijoe** [comment]
That `main` was leftover from my package boilerplate. It was only meant to be used as a CLI. You can import the `type-syncer` if you want but I don't provide any API stability guarantees. I don't change it a lot though.
