### ISSUE TITLE
typesync command hangs

### ISSUE THREAD

**Issue by raduchiriac** [jeffijoe/typesync#6]
node: 8.5.0
npm: 5.3.0
typesync: 0.2.5
OS: Windows 7 x64 — company PC yeah, I know :(

When I do `typesync` this message hangs with the spinning arrow. Using `--dry` is the same.
```
Syncing type definitions in package.json...
```

**Comment by jeffijoe** [comment]
Company PC eh? Could it be a firewall issue?

**Comment by raduchiriac** [comment]
No firewall here AFAIK 
Will check on another PC and close this if un-relevant.

Don't you have a `--verbose` type of thing?

**Comment by jeffijoe** [comment]
Not really, might be a good idea to add though!

**Comment by raduchiriac** [comment]
Debugged it and it stops at `createTypeDefinitionSource.fetch()`
Strange, it's for sure not the first package I own that uses **axios**

It does work on another network from my company. Must be a proxy issue for now.
