### ISSUE TITLE
Add `postinstall` script recommendation in readme

### ISSUE THREAD

**Issue by karlhorky** [jeffijoe/typesync#63]
Hi, thanks for this project, really cool!

What are your thoughts on using `typesync` in a `postinstall` script? So that `@types` packages are installed automatically?

If https://github.com/jeffijoe/typesync/issues/46 gets implemented with "removing unused types", then it may be a good idea to recommend [`postinstall-postinstall`](https://github.com/ds300/postinstall-postinstall) for users of Yarn.

**Comment by jeffijoe** [comment]
#46 should be possible now with the `--ignoredeps` option

**Comment by karlhorky** [comment]
Ok, and about the `postinstall` idea? Have any thoughts?

**Comment by jeffijoe** [comment]
I haven't tried it so I can't speak for it. I have heard, though, that postinstall are a can of worms.

**Comment by karlhorky** [comment]
Hm, ok. To be clear, I mean just adding this line to the `package.json`:

```diff
{
  "scripts": {
+    "postinstall": "typesync"
  }
}
```

This would cause the `typesync` command to be automatically run after each `npm install` or `yarn add`. [Example in npm docs](https://docs.npmjs.com/cli/v6/using-npm/scripts#examples).

**Comment by jeffijoe** [comment]
Sure. You can add it as a recommendation to the readme.

**Comment by karlhorky** [comment]
Maybe the recommended `postinstall` should actually be `typesync && yarn`, because of what @aequasi mentioned: https://github.com/jeffijoe/typesync/issues/44#issuecomment-768928750

**Comment by karlhorky** [comment]
Ok, opened #65 for this
