### ISSUE TITLE
Check packages for index.d.ts without `types` or `typings` field in package.json

### ISSUE THREAD

**Issue by karlhorky** [jeffijoe/typesync#64]
#24 implemented checks for internal types in packages, but it seems like it didn't address the case of a package with an `index.d.ts` but no `types` / `typings` field in `package.json`.

This is apparently allowed, according to TypeScript docs (and also used in the wild):

https://twitter.com/sindresorhus/status/1342368373296881664

**Comment by jeffijoe** [comment]
Is that file included in the files array of the package?

**Comment by karlhorky** [comment]
Yep, it is: https://unpkg.com/browse/ky@0.26.0/package.json

Is the `files` key also considered?

**Comment by jeffijoe** [comment]
I suppose a check for any `*.d.ts` will do in the files array.

**Comment by karlhorky** [comment]
Could you just check for the existence of `index.d.ts` on disk (in `node_modules`)? Or is there an issue with this?

**Comment by jeffijoe** [comment]
I would prefer not having to check node modules, currently everything works off of the package defs.

**Comment by jeffijoe** [comment]
Just so I understand the issue, you want the presence of `index.d.ts` in the `files` array to prevent the lookup of a `@types/` variant, similar to the presence of a `typings` field?

**Comment by karlhorky** [comment]
Yep, that seems like an accurate description 👍

**Comment by jeffijoe** [comment]
It seems even the NPM API doesn't return the `files` array either. So I think this is better solved by making packages specify their typings correctly in the package using `types` or `typings`.

**Comment by karlhorky** [comment]
Files on disk would be an alternative.

Also, there are other ways of doing it - eg. relying on a single request (either GET or HEAD) to the popular, performant CDN UNPKG:

- File exists (200-level response code): https://unpkg.com/ky@0.26.0/index.d.ts
- File doesn't exist (404 response code): https://unpkg.com/ky@0.26.0/not-there

I think it's a popular enough pattern in npm package publishing to put in some work to try to support it.

**Comment by jeffijoe** [comment]
Files on disk would not be deterministic, as there would be a difference between running typesync before or after an `npm install`

Using `unpkg` is an idea, but considering how I just got burned from using 2 different sources, I would rather stick to what npm returns.

[`ky` now includes](https://github.com/sindresorhus/ky/blob/53ce279c818998ed372822207b967eb68b92fba6/package.json#L16) the `types` field, by the way.
