### ISSUE TITLE
typesync Installs type dependencies which are not top level dependencies

### ISSUE THREAD

**Issue by fragm3** [jeffijoe/typesync#69]
For `"@types/testing-library__jest-dom"` and `"@types/testing-library__react-hooks"`, typesync installs these packages, these packages are not top-level dependency. They are already present in https://github.com/testing-library/jest-dom/blob/main/package.json and https://github.com/testing-library/react-hooks-testing-library/blob/master/package.json as a dependency. Can this be fixed? @jeffijoe 

Using these versions:   
    "@testing-library/jest-dom": "^5.11.6",
    "@testing-library/react-hooks": "^3.7.0",

**Comment by jeffijoe** [comment]
You can [use a config file](https://github.com/jeffijoe/typesync#use-config-file) to ignore those packages.

**Comment by fragm3** [comment]
@jeffijoe can you please see the issue again,

my package.json has 

`
    ...
    "devDependencies": {
    ...
      "@testing-library/jest-dom": "^5.11.6",
      "@testing-library/react-hooks": "^3.7.0"
    }
`

**Comment by jeffijoe** [comment]
I guess I don't understand the problem. If you have those 2 dependencies in your package.json, why wouldn't typesync install typings for them?

**Comment by fragm3** [comment]
@jeffijoe https://www.npmjs.com/package/@types/testing-library__react-hooks - @testing-library/react-hooks provides its own type definitions

**Comment by jeffijoe** [comment]
I haven't seen that way of "shipping typings" before. I think that is an edge case, so I suggest using the `ignorePackages` option.

**Comment by fragm3** [comment]
@jeffijoe can this be added to the roadmap for typesync? for now adding it in ignorePackages

**Comment by jeffijoe** [comment]
If it turns out that many other popular packages do it this way, then I would consider it. This is the first time I see it, and if everyone did it this way then TypeSync wouldn't be necessary. :)
